### ISSUE TITLE
Implement migrate openvpn page

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard.github.io#16]
Design: https://www.figma.com/design/uoFcgpOuVWa6g7tvKwB52o/defguard-01?node-id=7870-3757&t=dsKkE07z91tmV8r0-0

**Comment by teon** [comment]
URL Slug: /openvpn(.html)

**Comment by teon** [comment]
@cpprian site is great, already deployed.

But one component missing - please connect the form (and do form validation) to Update service via API.

@t-aleksander can you prepare a public endpoint like /crm/lead that we can post the data and the customer will have ,Prospect' status?

**Comment by teon** [comment]
@cpprian zrovilem merge I testuję ale nie działa...

**Comment by cpprian** [comment]
@teon https://github.com/DefGuard/defguard.github.io/pull/24
