### ISSUE TITLE
Display thank you & newsletter signing after client download

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard.github.io#38]
Here is the design: https://www.figma.com/design/uoFcgpOuVWa6g7tvKwB52o/defguard-01?node-id=5604-20256&node-type=CANVAS&t=CNcXM66sAR3cvwv6-0

**Comment by cpprian** [comment]
To finish this task we need https://github.com/DefGuard/defguard.github.io/issues/15 to be done

**Comment by teon** [comment]
@cpprian why?

**Comment by cpprian** [comment]
If we don't want to display `Privacy Notice and Privacy Policy` links this time, there is no any objections from my point of view
