### ISSUE TITLE
implement new download page

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard.github.io#5]
We have a "thank you for downloading" page - so after the download is clicked. But we need a download page for the client so that the user can choose what to download.
This is a great example that has everyting that is needed (version, changelog, clean choosing, call to action, options for a system like Intel/Apple silicon) - terms and conditions - so please treat this example as spec:

https://zed.dev/download , https://www.notion.so/desktop

And **we should have a default / detected system/binary** for non-tech users & all downliad options for tech users.

After the download page is designed, we need to:

- [x] Add link in the enrollment email to this download page
- [x] Find a way on the download page to automatically detect what is the latest version of the client to add links automatically. Two ideas come to mind: 1) extend the update service to check github releases and prepare the API for that to return a JSON to be easly done on the download website 2) JS on the website itself. If the update-service would be extended then we could have direct download links in the desktop client as well (and not entered manually).

**Comment by 4lb** [comment]
Design in figma -> https://www.figma.com/design/uoFcgpOuVWa6g7tvKwB52o/defguard-01?node-id=7459-2056&t=isOEzFHxJdmoBZ0M-11

On top we should present recognized system download button.

**Comment by teon** [comment]
@cpprian few things:

1. We detect what system user now uses and on first place we show download for that system and two other below.

2. Download for Mac has a select: Apple silicon, Intel 

3. Linux has a select: Debian/Ununtu package, RPM package

**Comment by t-aleksander** [comment]
release info endpoint:
https://api.github.com/repos/defguard/defguard/releases

docs:
https://docs.github.com/en/rest/releases/releases
