### ISSUE TITLE
Implement new pricing header

### ISSUE THREAD

**Issue by teon** [DefGuard/defguard.github.io#9]
As much as we would like defguard to be absolutely free and completely open source for everyone, to have the possibility to work and create defguard we have an open core &  paid license for some business features.
But there are exceptions to that, if you are a:

- student
- non profit organisation
- open source project
- startup

Please contact [us for a free license](link to google form).

@4lb would be good to underline/popup the 4 groups..

**Comment by 4lb** [comment]
design -> https://www.figma.com/design/uoFcgpOuVWa6g7tvKwB52o/defguard-01?node-id=5973-34532&t=M3kX5PGA9Q1wG4Tg-11

**Comment by cpprian** [comment]
assigned @teon to add link to google from

**Comment by teon** [comment]
@t-aleksander please merge the pricing header branch with my current pricing I've done.
The new header from that branch is relevant.
